### ISSUE TITLE
ICU4X Collation failures

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/conformance#129]
ICU4X in conformance testing shows more that 20% of the tests failing, seen here:
[ICU4X/icu73](https://unicode-org.github.io/conformance/rust/icu73/collation_short/verifier_test_report.html)

The actual collator options are seen in the test failure detail, with a few examples here. The inputs are s1 and s2 and the actual options used are given

- {"label":"0010001","s1":"𑜿!","s2":"𑜿?","line":8661,"ignorePunctuation":true}	CollatorOptions { strength: Some(Tertiary), alternate_handling: Some(Shifted), case_first: None, max_variable: None, case_level: None, numeric: None, backward_second_level: None }
- {"label":"0243300","s1":"𑛁b","s2":"𑜱b","line":47434}	CollatorOptions { strength: Some(Tertiary), alternate_handling: None, case_first: None, max_variable: None, case_level: None, numeric: None, backward_second_level: None }
- {"label":"0373766","s1":"龜a","s2":"龜a","line":177900}	CollatorOptions { strength: Some(Tertiary), alternate_handling: None, case_first: None, max_variable: None, case_level: None, numeric: None, backward_second_level: None }

We need some help debugging help with this!

**Comment by sffc** [comment]
Hey @hsivonen, can you take a look at these? Here is how we configure the ICU4X collator:

```rust
    let mut options = CollatorOptions::new();
    options.strength = Some(Strength::Tertiary);

    // Ignore punctuation only if using shifted test.
    if let Some(ip) = ignore_punctuation {
        if *ip {
            options.alternate_handling = Some(AlternateHandling::Shifted);
        }
    }

    let collator: Collator = Collator::try_new(&locale!("en").into(), options).unwrap();

    let comparison = collator.compare(str1, str2);
```

https://github.com/unicode-org/conformance/blob/34f5f0cee5cacc1d438a05833459feabd5cdf767/executors/rust/src/collator.rs#L17

Here is the corresponding JS code which passes the tests:

```javascript

    // Locale if provided in the test data.
    let testLocale = undefined;
    if ('locale' in json) {
      testLocale = json['locale'];
    }
    let testCollOptions = {};
    if ('ignorePunctuation' in json) {
      testCollOptions = {
        ignorePunctuation:json['ignorePunctuation']}
    }

    // Get other fields if provided
    let rules = undefined;
    if ('rules' in json) {
      rules = json['rules'];
    }

    // Set up collator object with optional locale and testOptions.
    let coll;
    try {
      coll = new Intl.Collator(testLocale, testCollOptions);

      let d1 = json['s1'];
      let d2 = json['s2'];

      const compared = coll.compare(d1, d2);
```

https://github.com/unicode-org/conformance/blob/34f5f0cee5cacc1d438a05833459feabd5cdf767/executors/node/collator.js#L9

These cases have no locale option so I don't have reason to believe that the locale is at fault.

Can you advise on how to get the Intl.Collator behavior via ICU4X APIs?

**Comment by hsivonen** [comment]
Do I understand correctly that your harness wants the outcome for all these three to be `Less`, but the outcome is `Equal`? If so, why is `Less` expected?

> * {"label":"0010001","s1":"𑜿!","s2":"𑜿?","line":8661,"ignorePunctuation":true}	CollatorOptions { strength: Some(Tertiary), alternate_handling: Some(Shifted), case_first: None, max_variable: None, case_level: None, numeric: None, backward_second_level: None }

These are `Equal`, because the inputs only differ by punctuation, the mechanism for ignoring punctuation is shifting punctuation to the quaternary level and you only compare on the tertiary level.

> * {"label":"0243300","s1":"𑛁b","s2":"𑜱b","line":47434}	CollatorOptions { strength: Some(Tertiary), alternate_handling: None, case_first: None, max_variable: None, case_level: None, numeric: None, backward_second_level: None }

These are `Equal`, because both strings are the same.

> * {"label":"0373766","s1":"龜a","s2":"龜a","line":177900}	CollatorOptions { strength: Some(Tertiary), alternate_handling: None, case_first: None, max_variable: None, case_level: None, numeric: None, backward_second_level: None }

These are `Equal`, because both compatibility ideographs normalize to U+9F9C, and the collator always normalizes.

**Comment by hsivonen** [comment]
I timed out on attempting to run the tests locally. Anyway, my guess is that this is a test harness bug, and the most suspicious part of the test harness is [this bit](https://github.com/unicode-org/conformance/blob/34f5f0cee5cacc1d438a05833459feabd5cdf767/executors/rust/src/collator.rs#L31-L37):
```rust
    let result = comparison == Ordering::Less;


    // TODO: How to do this easier?
    let mut result_string = true;
    if !result {
        result_string = false;
    }
```

**Comment by sffc** [comment]
Thank you @hsivonen!

Yeah, @sven-oly, here is a difference in code:

In Rust you say:

```rust
let result = comparison == Ordering::Less;
```

In JS you say:

```javascript
      let result_bool = true;
      if (compared > 0) {
        result_bool = false;
      }
```

So it appears perhaps Rust is looking for `<` and JS is looking for `<=`

**Comment by sven-oly** [comment]
We should be checking for less or equal. I can fix this next week. Tnx for
looking. Are there other sources of failures?

Craig

**Comment by sven-oly** [comment]
This was resolved by using <= instead of < as the test.
