### ISSUE TITLE
ICU4J LikelySubtags reveals strange behavior in ICU4J

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/conformance#196]
ICU4J Locale apparently does not accept "_" as the separator in locale tags, e.g.,
    {"test_type": "likely_subtags", "label":"0004","locale":"af_AQ","option":"minimize"}
resulting in "und" as the minimized locale.

However, this test works, giving "af-AQ" as expected:
    {"test_type": "likely_subtags", "label":"0004","locale":"af-AQ","option":"minimize"}

Something seems wrong with ICU4J's handling of many locales with Likely Subtags.

**Comment by sffc** [comment]
I think testdata gen should normalize these locales into BCP-47 (with hyphens). It is not interesting to test syntax parsing in the likely subtags test.

**Comment by echeran** [comment]
Duplicated by #199
