### ISSUE TITLE
Add linting for C++ code

### ISSUE THREAD

**Issue by echeran** [unicode-org/conformance#234]
We should add a C++ linter, as #228 suggests. According to https://github.com/unicode-org/conformance/pull/228#issuecomment-2113706594, the industry standard is `clang-tidy`.

We should ensure that the dependencies for this are in our setup script, and that we add this to CI (or our end-to-end script in CI).

**Comment by sven-oly** [comment]
What about this GItHub action? https://github.com/HorstBaerbel/action-clang-tidy

**Comment by sven-oly** [comment]
Applying this command fixes some things:
   clang-tidy --checks='modernize*, readability*'  *.cpp --fix-errors

**Comment by sven-oly** [comment]
Does this mean we would apply C++ linting in the continuous integration?

**Comment by sffc** [comment]
Yes, we should enforce the C++ linting in GitHub Actions.
