### ISSUE TITLE
Remove or update "Node.js 18 sample tests" - deprecated version of Node.

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/conformance#250]
[Run Node.js 18 sample tests](https://github.com/unicode-org/conformance/actions/runs/9899170766/job/27347576842)

The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Run Node.js 18 sample tests
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v2, actions/setup-node@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by sffc** [comment]
@sven-oly suggests deleting this test.

**Comment by sven-oly** [comment]
Removed in PR #284
