### ISSUE TITLE
Plural rules test data: there aren't any ORDINAL tests

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/conformance#260]
The test data should include original as well as cardinal tests.

**Comment by echeran** [comment]
When I look at the ICU4J executor passing tests (most them are passing) and looking at the characterization filter & results table, I see 870 ordinal tests.

Now, there are 5023 cardinal `plural_type` tests. Maybe we keep the issue open, but change the title to focus more specifically on this discrepancy?

**Comment by sffc** [comment]
I think it's _fine_ that there are not the same number of tests; cardinal rules are more commonly used and therefore have more data associated with them.
