### ISSUE TITLE
Refactor JS test data generating fns to use `.filter()` when sampling

### ISSUE THREAD

**Issue by echeran** [unicode-org/conformance#283]
This issue could become obsolete if/when we generate data straight from CLDR. But for now, with the JS code, we can:

1. Refactoring test data sampling code to a common function rather than reimplement that logic in each component's test data generator
2. Instead of manual logic for taking every nth element of a collection, [reuse JS's FP functions and a one-liner](https://github.com/unicode-org/conformance/pull/280/files#diff-798cf7dceb35a95386801e14d3977bf28f437aab15f8e1c8e1e3ceb67cec65cdR50) ([alternative formulation](https://stackoverflow.com/a/41312896/2077918)).

**Comment by sven-oly** [comment]
Working on this now.
