### ISSUE TITLE
Add ICU4J, NodeJS executors for CLDR 46 / ICU 76

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/conformance#303]

**Comment by sven-oly** [comment]
This should be done for ICU4J, ICU4X, and NodeJS when these are available

**Comment by sven-oly** [comment]
PR #348 adds NodeJS for ICU76.1 with version 23.3.0.

Note that ICU4X is the only outstanding required platform for ICU76.

**Comment by sven-oly** [comment]
We need ICU4X 2.0 support. I cannot do this myself, but need help!

**Comment by echeran** [comment]
ICU4X portion of the work has been extracted out into a separate issue #355 since it entails some extra work.
