### ISSUE TITLE
ICU4X and plural_rules: locale "root" gives an error.

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/conformance#307]

**Comment by sven-oly** [comment]
This data results in an error with {"test_type": "plural_rules", "option":"root"}

{"test_type": "plural_rules", "locale":"root","label":"308","type":"cardinal","plural_type":"cardinal","sample":"15","hexhash":"3c749a7b7dfd26b68537283d16e03d72b6f869d4"}

Should these tests with locale "root" be dropped or mapped to "und" or something else?

**Comment by sffc** [comment]
Please just remove locale "root" from the test data.

**Comment by echeran** [comment]
Removing `root` as a locale from test data is suggested in #318

**Comment by sven-oly** [comment]
This was fixedtoday  in PR#341.
