### ISSUE TITLE
Generate date time test data from CLDR sources

### ISSUE THREAD

**Issue by echeran** [unicode-org/conformance#324]

**Comment by sven-oly** [comment]
Will this be for data before ICU75?

**Comment by sffc** [comment]
Note: this issue is about reading the CLDR date time test data instead of generating the test data with Node.js. It can be done in parallel with efforts involving improvements to the CLDR test data.

**Comment by sven-oly** [comment]
PR #329 references this. However, the data generation needs to be examined because many test failures occur when comparing ICU4J/C/X output with the expected text.

**Comment by sven-oly** [comment]
This was fixed in PR #329. Many tests are now known issues. There are still questions, however, e.g., Arabic vs. ASCII comma.
