### ISSUE TITLE
More flexible source data download in testdata generator

### ISSUE THREAD

**Issue by echeran** [unicode-org/conformance#42]
`testdata_gen.py` hardcodes the source of data using a Github URL for a file from a specific version of ICU: https://github.com/unicode-org/conformance/blob/main/testgen/testdata_gen.py#L334

Instead, we should:

- Options to de-flake the download process
  * Separate the download step from the data generation step
  * Enable option to download a file vs. using a local copy
  * Show user a display of download progress
- Handle versioning of data (allow different versions of input)

**Comment by sven-oly** [comment]
PR #68 introduces multiple test data sources for icu68 - icu73. It introduces --icu_version as a testdriver argument which selects the data version to be used. Multiple versions can be included which all are used with the same version of the text executor, which can be set with nvm, e.g. `nvm use 20.1`.

**Comment by sven-oly** [comment]
Resolving this.
