### ISSUE TITLE
Define schema of test case data JSON

### ISSUE THREAD

**Issue by echeran** [unicode-org/conformance#43]
Some options for defining a schema:

- JSON Schema
- Protobuf

JSON Schema is a natural first choice. Also, it would take more effort to deal with Protobuf (perhaps too prohibitive in statically typed languages, even if possible in dynamic ones).

Only need to have a single tool to use JSON Schema since purpose is to validate once the JSON test data cases generated by the test generation tool.

**Comment by sven-oly** [comment]
PR#101 defines schema for test data and test results. It's not yet integrated into the workflow.

**Comment by sven-oly** [comment]
This is now implemented. It runs in the generate script, checking schemas, test data, and test output.
