### ISSUE TITLE
Rename 'rust' to 'icu4x' in testdriver, executor code

### ISSUE THREAD

**Issue by echeran** [unicode-org/conformance#62]
The code has been using "Rust" instead of "ICU4X". We should rename accordingly.

Since the thing under test is an i18n library, we should rename our code according to the library name under test. The version number of the language runtime needed for the library version is a separate thing, and may not correspond 1:1 anyways (ex: ICU4X 1.0 and ICU4X 1.1 were developed against Rust 1.61, ICU4X 1.2 was developed against Rust 1.68.2).

**Comment by sven-oly** [comment]
The display of the summary and detail pages now refer to "ICU4X".
