### ISSUE TITLE
Must deal with missing or incorrect icu testdata version

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/conformance#68]
The testdriver code assumes that the --icu_version parameter for the test driver is defined and that it refers to existing data. However, the value may be missing or may not be one of the defined test sets.

Proposed solution: check all defined testdata directories. If icu_version is not defined or a bad value is given, use the highest number ICU version, e.g., a value of "xyz" will look at subdirectory names and pick the one that sorts highest.

For example, if the directories are [icu73, icu72, and icu71], a missing or incorrect value for icu_version will select icu73 data for testing.

**Comment by sffc** [comment]
This issue no longer makes sense. We should upstream all our data generation to CLDR and use those versions, not auto-select old versions.
