### ISSUE TITLE
Add likely subtags tests

### ISSUE THREAD

**Issue by sffc** [unicode-org/conformance#89]
CLDR is adding test data for likely subtags:

https://github.com/unicode-org/cldr/pull/3173

We have support for this in both Intl and ICU4X. It would be a good test to add.

**Comment by sven-oly** [comment]
Being implemented in https://github.com/unicode-org/conformance/pull/93

**Comment by sven-oly** [comment]
This is now in place for Dart Web and for NodeJS. It's not yet working in ICU4X.

**Comment by sven-oly** [comment]
Now working in all 3 platforms.
